FROM alpine:latest

RUN apk --no-cache add openssh-client

COPY tunnel.sh /tunnel.sh
COPY healthcheck-tunnel.sh /healthcheck-tunnel.sh
RUN chmod +x /tunnel.sh /healthcheck-tunnel.sh

ENTRYPOINT ["/tunnel.sh"]
